version: '3.9'
services:
  Exegesis AI-manager:
    build: .
    image: Exegesis AI/service-manager:latest
    ports:
      - "8000:8000"
      - "8100:8100"
      - "3000:3000"
      - "3300:3300"
      - "9101:9101"
    environment:
      - EXEGESIS_ENV=docker
    volumes:
      - ../..:/workspace
    working_dir: /workspace
    command: ["pwsh", "-NoLogo", "-NoProfile", "-File", "start-Exegesis AI.ps1", "-ActiveDeploymentColor", "blue"]
